server:
  port: 8114
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 7
#    timeout: 180000
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 5
#        min-idle: 0
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dcd_admin?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      database: 10
#      timeout: 180000
#      lettuce:
#        pool:
#          max-active: 20
#          max-wait: -1
#          max-idle: 5
#          min-idle: 0
#  cloud:
#    nacos:
#      discovery:
#        register-enabled: true
#        server-addr: 175.27.191.217:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.chongdong.model
